name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format
      - uses: stefanzweifel/git-auto-commit-action@v6